service: epsagon-lambda-extension-example

provider:
  name: aws
  runtime: nodejs12.x

custom:
  epsagon:
    token: your-token
    appName: test-extension

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:066549572091:layer:epsagon-extension-js-layer:17

plugins:
  - serverless-plugin-epsagon
